sonar.projectKey=HMS_Sprint4_Backend
sonar.projectName=HMS_Sprint4_Backend
Node App sonar.projectVersion=1.0
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8
# Exclusions
sonar.exclusions=node_modules/**,test/**
# Test coverage
sonar.coverage.exclusions = **
# sonar.tests=test sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Server & auth
sonar.host.url=http://localhost:9000
sonar.login= sqp_76769f720f7d5526145091a93c50a7005d7b8f5f