const STATUS = Object.freeze({
  ACTIVE: "ACTIVE", INACTIVE: "INACTIVE",
  BOOKED: "BOOKED", CANCELLED: "CANCELLED", COMPLETED: "COMPLETED",
  PENDING: "PENDING", PAID: "PAID",REJECTED: "REJECTED",IN_CONSULTATION: "IN_CONSULTATION",NO_SHOW: "NO_SHOW",
});

module.exports = STATUS;