const STATUS = Object.freeze({
  ACTIVE: "ACTIVE", INACTIVE: "INACTIVE",
  BOOKED: "BOOKED", CANCELLED: "CANCELLED", COMPLETED: "COMPLETED",
  PENDING: "PENDING", PAID: "PAID",
});

module.exports = STATUS;