name: Deploy HMS Backend

on:
  push:
    branches:
      - feature/visagan_sprint_5

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_VISAGAN_HOST }}
          username: ${{ secrets.EC2_VISAGAN_USER }}
          key: ${{ secrets.EC2_VISAGAN_SSH }}
          script: |
            cd hms_project/HMS_backend
            git pull origin feature/visagan_sprint_5
            npm ci
            pm2 restart hms_backend || pm2 start src/server.js --name hms_backend
            pm2 save
